package com.empresa.area.libranzasrg;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("objeto de datos con la información propia del cliente")
public class cliente implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("categoria_contrato")
   @org.kie.api.definition.type.Description("vamos a tenr 3 categorías CAT1 (Provisional, vacante definitiva y libre nombramiento y remoción), CAT2(Trabajador oficial o dle sector público) y CAT3(Sector público)")
   private java.lang.String categoria_contrato;
   @org.kie.api.definition.type.Label("causa_pension")
   @org.kie.api.definition.type.Description("las personas se pueden pensionar basicamente: Indefinido, fijo y pensionado.")
   private java.lang.String causa_pension;
   @org.kie.api.definition.type.Label("edad")
   @org.kie.api.definition.type.Description("edad del cliente en años")
   private java.lang.Integer edad;
   @org.kie.api.definition.type.Label("id")
   @org.kie.api.definition.type.Description("Identificación del cliente, se espera que sea un numero uúnico (cedula o céula de exgtranejría).")
   private java.lang.Long id;
   @org.kie.api.definition.type.Label("modalidad-contrato")
   @org.kie.api.definition.type.Description("tres modalidades INDEFINIDO, FIJO y PENSIONADO")
   private java.lang.String modalidad_contrato;
   @org.kie.api.definition.type.Label("pension")
   @org.kie.api.definition.type.Description("variable que indica si es o no pensionado")
   private java.lang.Boolean pension;
   @org.kie.api.definition.type.Label("respuesta_cr")
   @org.kie.api.definition.type.Description("Es la respuesta del buró de crédito, en la que toma valores 0, 4 y 7 cuando no tiene experiencia crediticia, pero igual es atendido por el Banco.")
   private java.lang.Integer respuesta_cr;
   @org.kie.api.definition.type.Label("score")
   @org.kie.api.definition.type.Description("score de la central de riesgo que toma valores entre 150 y 950")
   private java.lang.Integer score;
   @org.kie.api.definition.type.Label("smmlv")
   @org.kie.api.definition.type.Description("valor del salario mínimo en número de salarios.")
   private java.lang.Float smmlv;
   @org.kie.api.definition.type.Label("tipo_id")
   @org.kie.api.definition.type.Description("tipo de identificación si es CC o CE")
   private java.lang.Integer tipo_id;

   public cliente()
   {
   }

   public java.lang.String getCategoria_contrato()
   {
      return this.categoria_contrato;
   }

   public void setCategoria_contrato(java.lang.String categoria_contrato)
   {
      this.categoria_contrato = categoria_contrato;
   }

   public java.lang.String getCausa_pension()
   {
      return this.causa_pension;
   }

   public void setCausa_pension(java.lang.String causa_pension)
   {
      this.causa_pension = causa_pension;
   }

   public java.lang.Integer getEdad()
   {
      return this.edad;
   }

   public void setEdad(java.lang.Integer edad)
   {
      this.edad = edad;
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getModalidad_contrato()
   {
      return this.modalidad_contrato;
   }

   public void setModalidad_contrato(java.lang.String modalidad_contrato)
   {
      this.modalidad_contrato = modalidad_contrato;
   }

   public java.lang.Boolean getPension()
   {
      return this.pension;
   }

   public void setPension(java.lang.Boolean pension)
   {
      this.pension = pension;
   }

   public java.lang.Integer getRespuesta_cr()
   {
      return this.respuesta_cr;
   }

   public void setRespuesta_cr(java.lang.Integer respuesta_cr)
   {
      this.respuesta_cr = respuesta_cr;
   }

   public java.lang.Integer getScore()
   {
      return this.score;
   }

   public void setScore(java.lang.Integer score)
   {
      this.score = score;
   }

   public java.lang.Float getSmmlv()
   {
      return this.smmlv;
   }

   public void setSmmlv(java.lang.Float smmlv)
   {
      this.smmlv = smmlv;
   }

   public java.lang.Integer getTipo_id()
   {
      return this.tipo_id;
   }

   public void setTipo_id(java.lang.Integer tipo_id)
   {
      this.tipo_id = tipo_id;
   }

   public cliente(java.lang.String categoria_contrato,
         java.lang.String causa_pension, java.lang.Integer edad,
         java.lang.Long id, java.lang.String modalidad_contrato,
         java.lang.Boolean pension, java.lang.Integer respuesta_cr,
         java.lang.Integer score, java.lang.Float smmlv,
         java.lang.Integer tipo_id)
   {
      this.categoria_contrato = categoria_contrato;
      this.causa_pension = causa_pension;
      this.edad = edad;
      this.id = id;
      this.modalidad_contrato = modalidad_contrato;
      this.pension = pension;
      this.respuesta_cr = respuesta_cr;
      this.score = score;
      this.smmlv = smmlv;
      this.tipo_id = tipo_id;
   }

}