package com.empresa.area.libranzasrg;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("empresa")
@org.kie.api.definition.type.Description("Objeto de datos con información del tipo de empresa en la cual se encuentra laborando el cliente")
public class empresa implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("convenio")
   private java.lang.String convenio;
   @org.kie.api.definition.type.Label("tipo")
   @org.kie.api.definition.type.Description("las empresas pueden ser o PUBLICAS o PRIVADAS")
   private java.lang.String tipo;

   public empresa()
   {
   }

   public java.lang.String getConvenio()
   {
      return this.convenio;
   }

   public void setConvenio(java.lang.String convenio)
   {
      this.convenio = convenio;
   }

   public java.lang.String getTipo()
   {
      return this.tipo;
   }

   public void setTipo(java.lang.String tipo)
   {
      this.tipo = tipo;
   }

   public empresa(java.lang.String convenio, java.lang.String tipo)
   {
      this.convenio = convenio;
      this.tipo = tipo;
   }

}