package com.empresa.area.libranzasrg;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("respuesta en vacío")
public class respuesta implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Description("la respuesta que va a arrojar el motor luegpo de evaluar la regla")
   @org.kie.api.definition.type.Label("resultado")
   private java.lang.String resultado;

   public respuesta()
   {
   }

   public java.lang.String getResultado()
   {
      return this.resultado;
   }

   public void setResultado(java.lang.String resultado)
   {
      this.resultado = resultado;
   }

   public respuesta(java.lang.String resultado)
   {
      this.resultado = resultado;
   }

}